
[build]
  command = "npm run build"
  #functions = "functions/"
  publish = "build"
  
[dev]
  command = "svelte-kit dev"

[[redirects]]
  from = "/m"
  to = "/produits"

[[redirects]]
  from = "/m/nous-contacter"
  to = "/contact"

[[redirects]]
  from = "/produits/lavabos-aseptiques"
  to = "/produits?level=1"

[[redirects]]
  from = "/mentions-legales"
  to = "/mentions"

[[redirects]]
  from = "/documentations"
  to = "/"