backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "../img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "produits" # Used in routes, e.g., /admin/collections/blog
    label: "Produits" # Used in the UI
    folder: "static/produits" # The path to the folder where our blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document
      - { label: "Layout", name: "layout", widget: "hidden", default: "produits"}
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Titre général", name: "title", widget: "string"}
      - { label: "Sous-titre général", name: "subtitle", widget: "string"}
      - { label: "Image de couverture", name: "thumbnail", widget: "image"}
      - { label: "Date de publication", name: "date", widget: "datetime"}
      - { label: "Tableau (optionnel, pour chaque ligne, séparer les colonnes par des virgules)", name: "tableau", widget: "list", field: {label: ligne, name: ligne, widget: string} }
      - label: 'Section'
        name: 'section'
        widget: 'list'
        types:
          - label: "Titre de section"
            name: "sectiontitle"
            widget: string
            default: 'Titre de la section'
            hint : 'Ligne 1 du titre de section sur FOND bleu'
          - label: "Sous-titre de section"
            name: "sectionsubtitle"
            widget: string
            default: 'Titre de la section'
            hint : 'Ligne 2 (+petite) du titre de section sur FOND bleu'
          - label: "Contenu"
            name: "contenu"
            widget: object
            fields: 
              - { label: "Intertitre grand", name: "interbig", widget: string }
              - { label: "Intertitre petit", name: "intersmall", widget: string }
              - { label: "Le +", name: "leplus", widget: text }
              - { label: "Corps", name: "body", widget: "markdown" }
              - { label: "Images", name: images, widget: list, field: { label: Image, name: image, widget: image }}